version: '2'
services:
  build:
    image: untangleinc/mfw:build
    volumes:
      - ./:/home/untangle/openwrt
    command: musl
  build-local-container:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./:/home/untangle/openwrt
    command: musl
